[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "splice"
version = "0.1.0"
description = "Compiles a typed subset of Python straight to native C++"
requires-python = ">=3.10"
dependencies = [
    # A fork of mypy 2.3.0 that supports more fixed-width int types
    # Normaly mypy can be compiled with mypyc but this uses the Python version by default (2x speed difference between compiled and interpreted but 5 minute compile time)
    # For the mypyc-compiled version reinstall with MYPY_USE_MYPYC=1 set:
    # MYPY_USE_MYPYC=1 pip install --force-reinstall --no-deps \
    #   "mypy @ git+https://github.com/omercanb/mypy-splice-fork.git@splice-fixed-width-promotion-clean"
    "mypy @ git+https://github.com/omercanb/mypy-splice-fork.git@splice-fixed-width-promotion-clean",
    "tabulate>=0.10",
]

[project.optional-dependencies]
test = [
    "pytest>=9.1",
    "syrupy>=5.5",
    "numpy>=2.5",
    "tqdm>=4.70",
    "mypy-extensions>=1.1",
    "typing-extensions>=4.16",
]

[tool.setuptools.package-data]
splice = ["runtime/*.h", "runtime/ankerl/*.h", "py.typed"]
