from typing import SupportsInt, TypeVar, Union

_T = TypeVar("_T")

def copy(value: _T) -> _T: ...
def _error_after_tree_transform(value: int) -> int: ...

_Int = Union[int, int8, uint8, int16, uint16, int32, uint32, int64, uint64]

class int8:
    def __init__(self, x: Union[_Int, str, bytes, SupportsInt], base: int = ...) -> None: ...
    def __add__(self, x: int8) -> int8: ...
    def __radd__(self, x: int8) -> int8: ...
    def __sub__(self, x: int8) -> int8: ...
    def __rsub__(self, x: int8) -> int8: ...
    def __mul__(self, x: int8) -> int8: ...
    def __rmul__(self, x: int8) -> int8: ...
    def __floordiv__(self, x: int8) -> int8: ...
    def __rfloordiv__(self, x: int8) -> int8: ...
    def __mod__(self, x: int8) -> int8: ...
    def __rmod__(self, x: int8) -> int8: ...
    def __and__(self, x: int8) -> int8: ...
    def __rand__(self, x: int8) -> int8: ...
    def __or__(self, x: int8) -> int8: ...
    def __ror__(self, x: int8) -> int8: ...
    def __xor__(self, x: int8) -> int8: ...
    def __rxor__(self, x: int8) -> int8: ...
    def __lshift__(self, x: int8) -> int8: ...
    def __rlshift__(self, x: int8) -> int8: ...
    def __rshift__(self, x: int8) -> int8: ...
    def __rrshift__(self, x: int8) -> int8: ...
    def __neg__(self) -> int8: ...
    def __invert__(self) -> int8: ...
    def __pos__(self) -> int8: ...
    def __lt__(self, x: int8) -> bool: ...
    def __le__(self, x: int8) -> bool: ...
    def __ge__(self, x: int8) -> bool: ...
    def __gt__(self, x: int8) -> bool: ...

class uint8:
    def __init__(self, x: Union[_Int, str, bytes, SupportsInt], base: int = ...) -> None: ...
    def __add__(self, x: uint8) -> uint8: ...
    def __radd__(self, x: uint8) -> uint8: ...
    def __sub__(self, x: uint8) -> uint8: ...
    def __rsub__(self, x: uint8) -> uint8: ...
    def __mul__(self, x: uint8) -> uint8: ...
    def __rmul__(self, x: uint8) -> uint8: ...
    def __floordiv__(self, x: uint8) -> uint8: ...
    def __rfloordiv__(self, x: uint8) -> uint8: ...
    def __mod__(self, x: uint8) -> uint8: ...
    def __rmod__(self, x: uint8) -> uint8: ...
    def __and__(self, x: uint8) -> uint8: ...
    def __rand__(self, x: uint8) -> uint8: ...
    def __or__(self, x: uint8) -> uint8: ...
    def __ror__(self, x: uint8) -> uint8: ...
    def __xor__(self, x: uint8) -> uint8: ...
    def __rxor__(self, x: uint8) -> uint8: ...
    def __lshift__(self, x: uint8) -> uint8: ...
    def __rlshift__(self, x: uint8) -> uint8: ...
    def __rshift__(self, x: uint8) -> uint8: ...
    def __rrshift__(self, x: uint8) -> uint8: ...
    def __neg__(self) -> uint8: ...
    def __invert__(self) -> uint8: ...
    def __pos__(self) -> uint8: ...
    def __lt__(self, x: uint8) -> bool: ...
    def __le__(self, x: uint8) -> bool: ...
    def __ge__(self, x: uint8) -> bool: ...
    def __gt__(self, x: uint8) -> bool: ...

class int16:
    def __init__(self, x: Union[_Int, str, bytes, SupportsInt], base: int = ...) -> None: ...
    def __add__(self, x: int16) -> int16: ...
    def __radd__(self, x: int16) -> int16: ...
    def __sub__(self, x: int16) -> int16: ...
    def __rsub__(self, x: int16) -> int16: ...
    def __mul__(self, x: int16) -> int16: ...
    def __rmul__(self, x: int16) -> int16: ...
    def __floordiv__(self, x: int16) -> int16: ...
    def __rfloordiv__(self, x: int16) -> int16: ...
    def __mod__(self, x: int16) -> int16: ...
    def __rmod__(self, x: int16) -> int16: ...
    def __and__(self, x: int16) -> int16: ...
    def __rand__(self, x: int16) -> int16: ...
    def __or__(self, x: int16) -> int16: ...
    def __ror__(self, x: int16) -> int16: ...
    def __xor__(self, x: int16) -> int16: ...
    def __rxor__(self, x: int16) -> int16: ...
    def __lshift__(self, x: int16) -> int16: ...
    def __rlshift__(self, x: int16) -> int16: ...
    def __rshift__(self, x: int16) -> int16: ...
    def __rrshift__(self, x: int16) -> int16: ...
    def __neg__(self) -> int16: ...
    def __invert__(self) -> int16: ...
    def __pos__(self) -> int16: ...
    def __lt__(self, x: int16) -> bool: ...
    def __le__(self, x: int16) -> bool: ...
    def __ge__(self, x: int16) -> bool: ...
    def __gt__(self, x: int16) -> bool: ...

class uint16:
    def __init__(self, x: Union[_Int, str, bytes, SupportsInt], base: int = ...) -> None: ...
    def __add__(self, x: uint16) -> uint16: ...
    def __radd__(self, x: uint16) -> uint16: ...
    def __sub__(self, x: uint16) -> uint16: ...
    def __rsub__(self, x: uint16) -> uint16: ...
    def __mul__(self, x: uint16) -> uint16: ...
    def __rmul__(self, x: uint16) -> uint16: ...
    def __floordiv__(self, x: uint16) -> uint16: ...
    def __rfloordiv__(self, x: uint16) -> uint16: ...
    def __mod__(self, x: uint16) -> uint16: ...
    def __rmod__(self, x: uint16) -> uint16: ...
    def __and__(self, x: uint16) -> uint16: ...
    def __rand__(self, x: uint16) -> uint16: ...
    def __or__(self, x: uint16) -> uint16: ...
    def __ror__(self, x: uint16) -> uint16: ...
    def __xor__(self, x: uint16) -> uint16: ...
    def __rxor__(self, x: uint16) -> uint16: ...
    def __lshift__(self, x: uint16) -> uint16: ...
    def __rlshift__(self, x: uint16) -> uint16: ...
    def __rshift__(self, x: uint16) -> uint16: ...
    def __rrshift__(self, x: uint16) -> uint16: ...
    def __neg__(self) -> uint16: ...
    def __invert__(self) -> uint16: ...
    def __pos__(self) -> uint16: ...
    def __lt__(self, x: uint16) -> bool: ...
    def __le__(self, x: uint16) -> bool: ...
    def __ge__(self, x: uint16) -> bool: ...
    def __gt__(self, x: uint16) -> bool: ...

class int32:
    def __init__(self, x: Union[_Int, str, bytes, SupportsInt], base: int = ...) -> None: ...
    def __add__(self, x: int32) -> int32: ...
    def __radd__(self, x: int32) -> int32: ...
    def __sub__(self, x: int32) -> int32: ...
    def __rsub__(self, x: int32) -> int32: ...
    def __mul__(self, x: int32) -> int32: ...
    def __rmul__(self, x: int32) -> int32: ...
    def __floordiv__(self, x: int32) -> int32: ...
    def __rfloordiv__(self, x: int32) -> int32: ...
    def __mod__(self, x: int32) -> int32: ...
    def __rmod__(self, x: int32) -> int32: ...
    def __and__(self, x: int32) -> int32: ...
    def __rand__(self, x: int32) -> int32: ...
    def __or__(self, x: int32) -> int32: ...
    def __ror__(self, x: int32) -> int32: ...
    def __xor__(self, x: int32) -> int32: ...
    def __rxor__(self, x: int32) -> int32: ...
    def __lshift__(self, x: int32) -> int32: ...
    def __rlshift__(self, x: int32) -> int32: ...
    def __rshift__(self, x: int32) -> int32: ...
    def __rrshift__(self, x: int32) -> int32: ...
    def __neg__(self) -> int32: ...
    def __invert__(self) -> int32: ...
    def __pos__(self) -> int32: ...
    def __lt__(self, x: int32) -> bool: ...
    def __le__(self, x: int32) -> bool: ...
    def __ge__(self, x: int32) -> bool: ...
    def __gt__(self, x: int32) -> bool: ...

class uint32:
    def __init__(self, x: Union[_Int, str, bytes, SupportsInt], base: int = ...) -> None: ...
    def __add__(self, x: uint32) -> uint32: ...
    def __radd__(self, x: uint32) -> uint32: ...
    def __sub__(self, x: uint32) -> uint32: ...
    def __rsub__(self, x: uint32) -> uint32: ...
    def __mul__(self, x: uint32) -> uint32: ...
    def __rmul__(self, x: uint32) -> uint32: ...
    def __floordiv__(self, x: uint32) -> uint32: ...
    def __rfloordiv__(self, x: uint32) -> uint32: ...
    def __mod__(self, x: uint32) -> uint32: ...
    def __rmod__(self, x: uint32) -> uint32: ...
    def __and__(self, x: uint32) -> uint32: ...
    def __rand__(self, x: uint32) -> uint32: ...
    def __or__(self, x: uint32) -> uint32: ...
    def __ror__(self, x: uint32) -> uint32: ...
    def __xor__(self, x: uint32) -> uint32: ...
    def __rxor__(self, x: uint32) -> uint32: ...
    def __lshift__(self, x: uint32) -> uint32: ...
    def __rlshift__(self, x: uint32) -> uint32: ...
    def __rshift__(self, x: uint32) -> uint32: ...
    def __rrshift__(self, x: uint32) -> uint32: ...
    def __neg__(self) -> uint32: ...
    def __invert__(self) -> uint32: ...
    def __pos__(self) -> uint32: ...
    def __lt__(self, x: uint32) -> bool: ...
    def __le__(self, x: uint32) -> bool: ...
    def __ge__(self, x: uint32) -> bool: ...
    def __gt__(self, x: uint32) -> bool: ...

class int64:
    def __init__(self, x: Union[_Int, str, bytes, SupportsInt], base: int = ...) -> None: ...
    def __add__(self, x: int64) -> int64: ...
    def __radd__(self, x: int64) -> int64: ...
    def __sub__(self, x: int64) -> int64: ...
    def __rsub__(self, x: int64) -> int64: ...
    def __mul__(self, x: int64) -> int64: ...
    def __rmul__(self, x: int64) -> int64: ...
    def __floordiv__(self, x: int64) -> int64: ...
    def __rfloordiv__(self, x: int64) -> int64: ...
    def __mod__(self, x: int64) -> int64: ...
    def __rmod__(self, x: int64) -> int64: ...
    def __and__(self, x: int64) -> int64: ...
    def __rand__(self, x: int64) -> int64: ...
    def __or__(self, x: int64) -> int64: ...
    def __ror__(self, x: int64) -> int64: ...
    def __xor__(self, x: int64) -> int64: ...
    def __rxor__(self, x: int64) -> int64: ...
    def __lshift__(self, x: int64) -> int64: ...
    def __rlshift__(self, x: int64) -> int64: ...
    def __rshift__(self, x: int64) -> int64: ...
    def __rrshift__(self, x: int64) -> int64: ...
    def __neg__(self) -> int64: ...
    def __invert__(self) -> int64: ...
    def __pos__(self) -> int64: ...
    def __lt__(self, x: int64) -> bool: ...
    def __le__(self, x: int64) -> bool: ...
    def __ge__(self, x: int64) -> bool: ...
    def __gt__(self, x: int64) -> bool: ...

class uint64:
    def __init__(self, x: Union[_Int, str, bytes, SupportsInt], base: int = ...) -> None: ...
    def __add__(self, x: uint64) -> uint64: ...
    def __radd__(self, x: uint64) -> uint64: ...
    def __sub__(self, x: uint64) -> uint64: ...
    def __rsub__(self, x: uint64) -> uint64: ...
    def __mul__(self, x: uint64) -> uint64: ...
    def __rmul__(self, x: uint64) -> uint64: ...
    def __floordiv__(self, x: uint64) -> uint64: ...
    def __rfloordiv__(self, x: uint64) -> uint64: ...
    def __mod__(self, x: uint64) -> uint64: ...
    def __rmod__(self, x: uint64) -> uint64: ...
    def __and__(self, x: uint64) -> uint64: ...
    def __rand__(self, x: uint64) -> uint64: ...
    def __or__(self, x: uint64) -> uint64: ...
    def __ror__(self, x: uint64) -> uint64: ...
    def __xor__(self, x: uint64) -> uint64: ...
    def __rxor__(self, x: uint64) -> uint64: ...
    def __lshift__(self, x: uint64) -> uint64: ...
    def __rlshift__(self, x: uint64) -> uint64: ...
    def __rshift__(self, x: uint64) -> uint64: ...
    def __rrshift__(self, x: uint64) -> uint64: ...
    def __neg__(self) -> uint64: ...
    def __invert__(self) -> uint64: ...
    def __pos__(self) -> uint64: ...
    def __lt__(self, x: uint64) -> bool: ...
    def __le__(self, x: uint64) -> bool: ...
    def __ge__(self, x: uint64) -> bool: ...
    def __gt__(self, x: uint64) -> bool: ...
